<a href="https://colab.research.google.com/github/XuRui314/HITSZ_2022_NLP_Project/blob/main/1_0_python_fund.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 提纲


本次实验课的主要内容有
- Python基础，数据处理库：Numpy, Pandas
- 简要介绍nltk
- 简要介绍gensim
- 通过以下三种方法实现一个简单的情感分类器
    - ngram特征+朴素贝叶斯
    - 情感词典
    - 词向量+SVM

###Python的对象类型

不可变类型：数字类型, 字符串, turples; 


可变类型： list, dictionary;


这部分也可以在这个[link](https://pythontutor.com/visualize.html#mode=display)可视化理解

In [ ]:
a = 2
print(id(a))
b = 3
print(id(b))
b = a
#数字不可变，赋引用，而不是赋值，a,b指向了同一片内存空间，而不是将值赋到b指向的空间内
print(id(b))

#同个数字的内存空间是相同的
c = 3
print(id(c))

#turples, string类似


94498130729504
94498130729536
94498130729504
94498130729536


In [ ]:
s = '1234'
print(s[0])
s[0]='k'
#string不可变，赋值出现错误

1


TypeError: 'str' object does not support item assignment

### 列表及切片

In [ ]:
a = [1,2,3,4,5,6,7,8]

print(a,type(a))


[1, 2, 3, 4, 5, 6, 7, 8] <class 'list'>


In [ ]:
a[-1]

8

In [ ]:
print(a[0 : ])
#左闭右开
print(a[0:-1])
print(a[0:3])

[1, 2, 3, 4, 5, 6, 7, 8]
[1, 2, 3, 4, 5, 6, 7]
[1, 2, 3]


### 字典

In [ ]:
dic = {'peter':2,'tom':4,'ketty':6}
print(dic.keys())
print(dic.values())

print('--------------------')
for k,v in dic.items():
    print(k,v)
print('--------------------')
for k in dic:
    print(k)

dict_keys(['peter', 'tom', 'ketty'])
dict_values([2, 4, 6])
--------------------
peter 2
tom 4
ketty 6
--------------------
peter
tom
ketty


### 函数

In [ ]:
def hello(num: int) -> str :
    #建议变量类型以及返回值类型
    sent_list =  [str(i+1) + ' hello world !\n' for i in range(num)]
    return ''.join(sent_list)
    # return 1
# for k in range(10):
#     print(k)
print(list(range(10)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
print(hello(num = 3))

1 hello world !
2 hello world !
3 hello world !



In [ ]:
print(hello('1'))

TypeError: ignored

在进行参数传递时，对于可变类型和不可变类型传递方式有所不同：

In [ ]:
def changeInt(x: int) -> int:
    
    print("函数内，计算前参数x的地址",id(x))

    x = x*x
    print("函数内，计算后参数x的地址",id(x))

    return x

t = 2
print(changeInt(t))
print("函数外，t的地址",id(t))
print(t)

函数内，计算前参数x的地址 94498130729504
函数内，计算后参数x的地址 94498130729568
4
函数外，t的地址 94498130729504
2


In [ ]:
def changeInt(x: list)->list:
    print("函数内，计算前参数x的地址",id(x))
    x[0]=0
    print("函数内，计算后参数x的地址",id(x))

    return x

t = [1,2]
print(changeInt(t))
print("函数外，t的地址",id(t))
print(t)

函数内，计算前参数x的地址 140034408968832
函数内，计算后参数x的地址 140034408968832
[0, 2]
函数外，t的地址 140034408968832
[0, 2]


In [ ]:
#不定长参数
def manyArgs(a: int, *wargs, **kwargs):
    print(a)
    print("元组收集参数",wargs)
    print("字典收集参数",kwargs)
    # print(w)

manyArgs(1, *(1,2,3,4),**{'w':1,'v':2})
manyArgs(2)
manyArgs(2,4,i=1,j=2,k=3,m=4)


1
元组收集参数 (1, 2, 3, 4)
字典收集参数 {'w': 1, 'v': 2}
2
元组收集参数 ()
字典收集参数 {}
2
元组收集参数 (4,)
字典收集参数 {'i': 1, 'j': 2, 'k': 3, 'm': 4}


### 类

In [ ]:
class Pet:
    def __init__(self, species, name):
        self.species = species
        self.name = name
        print("Now you have a {}! (PET)".format(self.species))

    def __str__(self):
        return f"{self.name} is a {self.species}. (PET)"

        


In [ ]:
tom_cat = Pet("blue cat","Tom")

print(tom_cat)

Now you have a blue cat! (PET)
Tom is a blue cat. (PET)


In [ ]:
class Cat(Pet):
    def __init__(self, species, name, color):
        
        super().__init__("Cat", name)

        self.color = color
        print(f"Now you have a {self.color} cat!")
        
    def call(self):
        print(f"{self.name} just mewed!")


In [ ]:
tony_cat = Cat("cat", 'tony',"black")

print(tony_cat)

tony_cat.call()

Now you have a Cat! (PET)
Now you have a black cat!
tony is a Cat. (PET)
tony just mewed!


## numpy
支持大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。



In [ ]:
import numpy as np

In [ ]:
#设置随机种子，如果不设置随机种子会导致结果无法复现
np.random.seed(seed=42)

#【1,2,3,4】
#1 
#4
#...

#1
#4
#...

In [ ]:
# Scalar
x = np.array(6) # scalar
print ("x: ", x)
# Number of dimensions
print ("x ndim: ", x.ndim)
# Dimensions
print ("x shape:", x.shape)
# Size of elements
print ("x size: ", x.size)
# Data type
print ("x dtype: ", x.dtype)

x:  6
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


In [ ]:
# Vector
x = np.array([1.3 , 2.2 , 1.7])
print ("x: ", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype) # notice the float datatype

x:  [1.3 2.2 1.7]
x ndim:  1
x shape: (3,)
x size:  3
x dtype:  float64


In [ ]:
# Matrix
x = np.array([[1,2], [3,4]],dtype=float)
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[1. 2.]
 [3. 4.]]
x ndim:  2
x shape: (2, 2)
x size:  4
x dtype:  float64


In [ ]:
# 3-D Tensor
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print ("x:\n", x)
print ("x ndim: ", x.ndim)
print ("x shape:", x.shape)
print ("x size: ", x.size)
print ("x dtype: ", x.dtype)

x:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


一些快速初始化array的函数

In [ ]:
# Functions
print ("np.zeros((2,2)):\n", np.zeros( (2,2) ) )
print ("np.ones((2,2)):\n", np.ones( (2,2) ))
print ("np.eye((2)):\n", np.eye( (2) )) # identity matrix 
print ("np.random.random((2,2)):\n", np.random.random( (2,2) ))

np.zeros((2,2)):
 [[0. 0.]
 [0. 0.]]
np.ones((2,2)):
 [[1. 1.]
 [1. 1.]]
np.eye((2)):
 [[1. 0.]
 [0. 1.]]
np.random.random((2,2)):
 [[0.37454012 0.95071431]
 [0.73199394 0.59865848]]


In [ ]:
# Indexing
x = np.array([1, 2, 3])

print ("x: ", x)
print ("x[0]: ", x[0])
x[0] = 0
print ("x: ", x)

x:  [1 2 3]
x[0]:  1
x:  [0 2 3]


In [ ]:
# Slicing
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print (x)
print ("x column 1: ", x[:, 1]) 
print ("x row 0: ", x[0, :]) 
print ("x rows 0,1 & cols 1,2: \n", x[0:2, 1:3]) 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x column 1:  [ 2  6 10]
x row 0:  [1 2 3 4]
x rows 0,1 & cols 1,2: 
 [[2 3]
 [6 7]]


In [ ]:
# Integer array indexing
print (x)
rows_to_get = np.array([0, 1, 2])
print ("rows_to_get: ", rows_to_get)
cols_to_get = np.array([0, 2, 1])
print ("cols_to_get: ", cols_to_get)
# Combine sequences above to get values to get
print ("indexed values: ", x[rows_to_get, cols_to_get]) # (0, 0), (1, 2), (2, 1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
rows_to_get:  [0 1 2]
cols_to_get:  [0 2 1]
indexed values:  [ 1  7 10]


In [ ]:
# Boolean array indexing

x = np.array([[1, 2], [3, 4], [5, 6]])

print ("x:\n", x)
print ("x > 2:\n", x > 2)
print ("x[x > 2]:\n", x[x > 2])

x:
 [[1 2]
 [3 4]
 [5 6]]
x > 2:
 [[False False]
 [ True  True]
 [ True  True]]
x[x > 2]:
 [3 4 5 6]


In [ ]:
# Basic math
x = np.array([[1,2], [3,4]], dtype=np.float64)
y = np.array([[1,2], [3,4]], dtype=np.float64)
print ("x + y:\n", np.add(x, y)) # or 
print(x + y)
print ("x - y:\n", np.subtract(x, y)) # or x - y
print ("x * y:\n", np.multiply(x, y)) # or 
x * y


x + y:
 [[2. 4.]
 [6. 8.]]
[[2. 4.]
 [6. 8.]]
x - y:
 [[0. 0.]
 [0. 0.]]
x * y:
 [[ 1.  4.]
 [ 9. 16.]]


array([[ 1.,  4.],
       [ 9., 16.]])

In [ ]:
# Dot product
a = np.array([[1,2,3], [4,5,6]], dtype=np.float64) # we can specify dtype
b = np.array([[7,8], [9,10], [11, 12]], dtype=np.float64)
c = a.dot(b)
print (f"{a.shape} · {b.shape} = {c.shape}")
print (c)

(2, 3) · (3, 2) = (2, 2)
[[ 58.  64.]
 [139. 154.]]


维度操作

In [ ]:
# Sum across a dimension
x = np.array([[1,2,3],[4,5,6]])
print (x)
print ("sum all: ", np.sum(x)) # adds all elements
print ("sum axis=0: ", np.sum(x, axis=0)) # sum across rows
print ("sum axis=1: ", np.sum(x, axis=1)) # sum across columns

[[1 2 3]
 [4 5 6]]
sum all:  21
sum axis=0:  [5 7 9]
sum axis=1:  [ 6 15]


In [ ]:
# Min/max
x = np.array([[1,2,3], [4,5,6]])
print ("min: ", x.min())
print ("max: ", x.max())
print ("min axis=0: ", x.min(axis=0))
print ("min axis=1: ", x.min(axis=1))

min:  1
max:  6
min axis=0:  [1 2 3]
min axis=1:  [1 4]


In [ ]:

x = np.random.random((5,2))

x

array([[0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258],
       [0.02058449, 0.96990985],
       [0.83244264, 0.21233911]])

In [ ]:
preds = x.argmax(axis=1)
# true_label


## pandas

Pandas 一个强大的分析结构化数据的工具集，基础是 Numpy（提供高性能的矩阵运算）。

Pandas 可以从各种文件格式比如 CSV、JSON、SQL、Microsoft Excel 导入数据。

In [2]:
import numpy as np
import pandas as pd

In [9]:
# 这里用colab的话是要先上传一下数据集的，在/content/sample_data这个目录
# df = pd.read_csv('sample_data/train_data_public.csv', encoding='utf-8',header=0)
df = pd.read_csv('train_data_public.csv', encoding='utf-8',header=0)

In [11]:
df.head()

id                                               text  \
0   0  交行14年用过，半年准备提额，却直接被降到1Ｋ，半年期间只T过一次三千，其它全部真实消费，第...   
1   1                                单标我有了，最近visa双标返现活动好   
2   2                                        建设银行提额很慢的……   
3   3                 我的怎么显示0.25费率，而且不管分多少期都一样费率，可惜只有69k   
4   4                                           利率不错，可以撸   

                                            BIO_anno  class  
0  B-BANK I-BANK O O O O O O O O O O B-COMMENTS_N...      0  
1  B-PRODUCT I-PRODUCT O O O O O O B-PRODUCT I-PR...      1  
2  B-BANK I-BANK I-BANK I-BANK B-COMMENTS_N I-COM...      0  
3  O O O O O O O O O O B-COMMENTS_N I-COMMENTS_N ...      2  
4  B-COMMENTS_N I-COMMENTS_N B-COMMENTS_ADJ I-COM...      1

In [12]:
print(type(df),type(df['text']))

<class 'pandas.core.frame.DataFrame'> <class 'pandas.core.series.Series'>


In [13]:
df['append'] = pd.Series(['append']*(len(df)//2))
# d = {'2':3}
# d['3']=4

In [14]:
df.head()

id                                               text  \
0   0  交行14年用过，半年准备提额，却直接被降到1Ｋ，半年期间只T过一次三千，其它全部真实消费，第...   
1   1                                单标我有了，最近visa双标返现活动好   
2   2                                        建设银行提额很慢的……   
3   3                 我的怎么显示0.25费率，而且不管分多少期都一样费率，可惜只有69k   
4   4                                           利率不错，可以撸   

                                            BIO_anno  class  append  
0  B-BANK I-BANK O O O O O O O O O O B-COMMENTS_N...      0  append  
1  B-PRODUCT I-PRODUCT O O O O O O B-PRODUCT I-PR...      1  append  
2  B-BANK I-BANK I-BANK I-BANK B-COMMENTS_N I-COM...      0  append  
3  O O O O O O O O O O B-COMMENTS_N I-COMMENTS_N ...      2  append  
4  B-COMMENTS_N I-COMMENTS_N B-COMMENTS_ADJ I-COM...      1  append

In [15]:
df = df.fillna('filled_text')

# Filtering

In [16]:
# Selecting data by feature
df['BIO_anno'].head()
# print(type())

0    B-BANK I-BANK O O O O O O O O O O B-COMMENTS_N...
1    B-PRODUCT I-PRODUCT O O O O O O B-PRODUCT I-PR...
2    B-BANK I-BANK I-BANK I-BANK B-COMMENTS_N I-COM...
3    O O O O O O O O O O B-COMMENTS_N I-COMMENTS_N ...
4    B-COMMENTS_N I-COMMENTS_N B-COMMENTS_ADJ I-COM...
Name: BIO_anno, dtype: object

In [17]:
# Filtering
df[ df['class']==0 ].head() # only the neural data extracted

id                                               text  \
0    0  交行14年用过，半年准备提额，却直接被降到1Ｋ，半年期间只T过一次三千，其它全部真实消费，第...   
2    2                                        建设银行提额很慢的……   
7    7  羡慕，可能上个月申请多了。上月连续下了浦发广发华夏交通。这个月申请建行，农业??邮储各种秒拒...   
8    8  这个短债只是用来提升信誉刷建行预审批的，又不是什么赚钱的基金。也只有建行有卖，我买过，不但不...   
10  10  这几天也接到了建行的分期电话，让我1.6分12期，跟他说5000，3期，意思意思。快两年了还...   

                                             BIO_anno  class  append  
0   B-BANK I-BANK O O O O O O O O O O B-COMMENTS_N...      0  append  
2   B-BANK I-BANK I-BANK I-BANK B-COMMENTS_N I-COM...      0  append  
7   O O O O O O O O O O O O O O O O O O O B-BANK I...      0  append  
8   O O B-PRODUCT I-PRODUCT O O O O B-COMMENTS_ADJ...      0  append  
10  O O O O O O O B-BANK I-BANK O B-PRODUCT I-PROD...      0  append

In [18]:
df[ df['append'] != 'append' ].head()

id                                               text  \
3764  3764                                   我没U盾可以加新卡啊，验证码就行   
3765  3765                    啊，这段时间说我名下没有可手动调额的卡。就是因为这个没有U盾？   
3766  3766                                   工行农行招行盾在手??其他没得了   
3767  3767  就是柜员或网点的个人行为吧；我要盾没用，去办卡说盾就给了，也没要钱，我同事密码器已不够用了，...   
3768  3768         一个月转转限额100万，去补个盾还没有，真是店大欺客，废了以后改用招商方便，服务也好   

                                               BIO_anno  class       append  
3764    O O B-PRODUCT I-PRODUCT O O O O O O O O O O O O      2  filled_text  
3765  O O O O O O O O O O O O O O O O O O O O O O O ...      2  filled_text  
3766  B-BANK I-BANK B-BANK I-BANK B-BANK I-BANK B-PR...      2  filled_text  
3767  O O O O O O O O O O O O O O O O O O O O O O O ...      2  filled_text  
3768  O O O O O O O O O O O O O O O O O O O O B-COMM...      0  filled_text

# Save data

In [19]:
# Saving dataframe to CSV
#,
# 这里要用ide打开csv文件，如果用wps显示不出来
df.to_csv('preprocessed_train.csv', sep=",",index=False)